# -*- coding: utf-8 -*-
"""Tutorial 2 & 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwEBwZ5fNDoZNaJA63iLO0wQqtM0E5r8
"""

# MLP CLASSIFIER - TUTORIAL 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Dataset shape:", X.shape)
print("Number of classes:", len(np.unique(y)))
print("Class names:", iris.target_names)

# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Standardize the features
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training samples:", X_train_scaled.shape[0])
print("Testing samples:", X_test_scaled.shape[0])

# Original MLP model from the tutorial

mlp = MLPClassifier(
    hidden_layer_sizes=(10, 10),
    activation='relu',
    solver='adam',
    learning_rate_init=0.001,
    max_iter=1000,
    random_state=42
)

# Train the model
mlp.fit(X_train_scaled, y_train)

# Predictions
y_pred = mlp.predict(X_test_scaled)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

# Classification report
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=iris.target_names
))

print("MLP MODEL INFORMATION")
print("=" * 40)

print("Number of hidden layers:", mlp.n_layers_ - 2)
print("Hidden layer sizes:", mlp.hidden_layer_sizes)
print("Activation function:", mlp.activation)
print("Output activation:", mlp.out_activation_)
print("Number of epochs:", mlp.n_iter_)
print("Final loss:", mlp.loss_)
print("Learning rate:", mlp.learning_rate_init)
print("Training accuracy:", mlp.score(X_train_scaled, y_train))
print("Testing accuracy:", mlp.score(X_test_scaled, y_test))

plt.figure(figsize=(8, 5))

plt.plot(
    mlp.loss_curve_,
    linewidth=2
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("MLP Learning Curve")
plt.grid(True)

plt.show()

# Different MLP architectures

architectures = {
    "1 layer - 5 neurons": (5,),
    "1 layer - 10 neurons": (10,),
    "1 layer - 20 neurons": (20,),
    "2 layers - 10,10": (10, 10),
    "2 layers - 20,20": (20, 20),
    "3 layers - 10,10,10": (10, 10, 10),
    "3 layers - 20,20,20": (20, 20, 20)
}

architecture_results = []

models = {}

for name, architecture in architectures.items():

    model = MLPClassifier(
        hidden_layer_sizes=architecture,
        activation='relu',
        solver='adam',
        learning_rate_init=0.001,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)

    architecture_results.append({
        "Architecture": name,
        "Test Accuracy": accuracy,
        "Epochs": model.n_iter_,
        "Final Loss": model.loss_
    })

    models[name] = model

# Convert results to dataframe
architecture_df = pd.DataFrame(architecture_results)

architecture_df

plt.figure(figsize=(10, 5))

plt.bar(
    architecture_df["Architecture"],
    architecture_df["Test Accuracy"]
)

plt.xlabel("Architecture")
plt.ylabel("Test Accuracy")
plt.title("Effect of MLP Architecture on Accuracy")

plt.xticks(rotation=45, ha='right')
plt.ylim(0, 1.05)
plt.grid(axis='y')

plt.show()

plt.figure(figsize=(12, 7))

for name, model in models.items():

    plt.plot(
        model.loss_curve_,
        label=name
    )

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Learning Curves for Different MLP Architectures")

plt.legend()
plt.grid(True)

plt.show()

# Different learning rates

learning_rates = [0.0001, 0.001, 0.01, 0.1]

learning_rate_results = []

lr_models = {}

for lr in learning_rates:

    model = MLPClassifier(
        hidden_layer_sizes=(10, 10),
        activation='relu',
        solver='adam',
        learning_rate_init=lr,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)

    learning_rate_results.append({
        "Learning Rate": lr,
        "Test Accuracy": accuracy,
        "Epochs": model.n_iter_,
        "Final Loss": model.loss_
    })

    lr_models[lr] = model

learning_rate_df = pd.DataFrame(learning_rate_results)

learning_rate_df

plt.figure(figsize=(10, 6))

for lr, model in lr_models.items():

    plt.plot(
        model.loss_curve_,
        label=f"Learning Rate = {lr}"
    )

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Effect of Learning Rate on MLP Convergence")

plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8, 5))

plt.bar(
    learning_rate_df["Learning Rate"].astype(str),
    learning_rate_df["Test Accuracy"]
)

plt.xlabel("Learning Rate")
plt.ylabel("Test Accuracy")
plt.title("Effect of Learning Rate on Test Accuracy")

plt.ylim(0, 1.05)
plt.grid(axis='y')

plt.show()

plt.figure(figsize=(8, 5))

plt.bar(
    learning_rate_df["Learning Rate"].astype(str),
    learning_rate_df["Epochs"]
)

plt.xlabel("Learning Rate")
plt.ylabel("Number of Epochs")
plt.title("Effect of Learning Rate on Number of Epochs")

plt.grid(axis='y')

plt.show()

print("=" * 70)
print("ARCHITECTURE COMPARISON")
print("=" * 70)

display(architecture_df)

print("\n")

print("=" * 70)
print("LEARNING RATE COMPARISON")
print("=" * 70)

display(learning_rate_df)