# -*- coding: utf-8 -*-
"""Tutorial 3 ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmdZA_lPrxJ9GP18Bx3Q94Zu66VV36T1
"""

# TUTORIAL 3: ANN FOR MNIST

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2

print("TensorFlow version:", tf.__version__)

# Load MNIST dataset

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

print("Training data:", X_train.shape)
print("Training labels:", y_train.shape)
print("Testing data:", X_test.shape)
print("Testing labels:", y_test.shape)

# Display some sample images

plt.figure(figsize=(10, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Normalize pixel values

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

print("Minimum pixel value:", X_train.min())
print("Maximum pixel value:", X_train.max())

# One-hot encoding

y_train_cat = tf.keras.utils.to_categorical(y_train, 10)
y_test_cat = tf.keras.utils.to_categorical(y_test, 10)

print("Original label:", y_train[0])
print("One-hot encoded:", y_train_cat[0])

# ORIGINAL MODEL

model = Sequential([
    Flatten(input_shape=(28, 28)),

    Dense(128, activation='relu'),

    Dense(64, activation='relu'),

    Dense(10, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train_cat,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# Evaluate on test data

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

# Plot accuracy

plt.figure(figsize=(8, 5))

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training vs Validation Accuracy')

plt.legend()
plt.grid(True)

plt.show()

# Plot loss

plt.figure(figsize=(8, 5))

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training vs Validation Loss')

plt.legend()
plt.grid(True)

plt.show()

# Make predictions

predictions = model.predict(X_test)

predicted_labels = np.argmax(predictions, axis=1)

print("Predicted:", predicted_labels[:20])
print("Actual:   ", y_test[:20])

# Visualize predictions

plt.figure(figsize=(12, 8))

for i in range(20):

    plt.subplot(4, 5, i + 1)

    plt.imshow(X_test[i], cmap='gray')

    plt.title(
        f"Actual: {y_test[i]}\nPredicted: {predicted_labels[i]}"
    )

    plt.axis('off')

plt.tight_layout()
plt.show()

def build_model(
    hidden_layers,
    activation='relu',
    optimizer='adam',
    dropout_rate=None,
    l2_rate=None
):

    model = Sequential()

    # Flatten layer
    model.add(Flatten(input_shape=(28, 28)))

    # Hidden layers
    for neurons in hidden_layers:

        if l2_rate is not None:

            model.add(
                Dense(
                    neurons,
                    activation=activation,
                    kernel_regularizer=l2(l2_rate)
                )
            )

        else:

            model.add(
                Dense(
                    neurons,
                    activation=activation
                )
            )

        # Optional dropout
        if dropout_rate is not None:
            model.add(Dropout(dropout_rate))

    # Output layer
    model.add(
        Dense(10, activation='softmax')
    )

    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

architectures = {
    "Original (128,64)": (128, 64),
    "One Layer (256)": (256,),
    "Two Layers (256,128)": (256, 128),
    "Three Layers (128,64,32)": (128, 64, 32),
    "Three Layers (256,128,64)": (256, 128, 64)
}

architecture_results = []
architecture_histories = {}

for name, layers in architectures.items():

    print("\nTraining:", name)

    temp_model = build_model(
        hidden_layers=layers,
        activation='relu',
        optimizer='adam'
    )

    temp_history = temp_model.fit(
        X_train,
        y_train_cat,
        epochs=10,
        batch_size=32,
        validation_split=0.2,
        verbose=0
    )

    loss, accuracy = temp_model.evaluate(
        X_test,
        y_test_cat,
        verbose=0
    )

    architecture_results.append({
        "Architecture": name,
        "Test Accuracy": accuracy,
        "Test Loss": loss,
        "Epochs": len(temp_history.history['loss'])
    })

    architecture_histories[name] = temp_history

architecture_results_df = pd.DataFrame(architecture_results)

architecture_results_df

import pandas as pd
plt.figure(figsize=(10, 5))

plt.bar(
    architecture_results_df["Architecture"],
    architecture_results_df["Test Accuracy"]
)

plt.xlabel("Architecture")
plt.ylabel("Test Accuracy")
plt.title("Comparison of Different ANN Architectures")

plt.xticks(rotation=45, ha='right')
plt.ylim(0, 1.05)

plt.grid(axis='y')

plt.show()

plt.figure(figsize=(10, 6))

for name, history in architecture_histories.items():

    plt.plot(
        history.history['val_accuracy'],
        label=name
    )

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy for Different Architectures")

plt.legend()
plt.grid(True)

plt.show()

import pandas as pd

activations = [
    'relu',
    'tanh',
    'sigmoid'
]

activation_results = []
activation_histories = {}

for activation in activations:

    print("\nTraining with:", activation)

    temp_model = build_model(
        hidden_layers=(128, 64),
        activation=activation,
        optimizer='adam'
    )

    temp_history = temp_model.fit(
        X_train,
        y_train_cat,
        epochs=10,
        batch_size=32,
        validation_split=0.2,
        verbose=0
    )

    loss, accuracy = temp_model.evaluate(
        X_test,
        y_test_cat,
        verbose=0
    )

    activation_results.append({
        "Activation": activation,
        "Test Accuracy": accuracy,
        "Test Loss": loss
    })

    activation_histories[activation] = temp_history

activation_df = pd.DataFrame(activation_results)

activation_df

plt.figure(figsize=(8, 5))

plt.bar(
    activation_df["Activation"],
    activation_df["Test Accuracy"]
)

plt.xlabel("Activation Function")
plt.ylabel("Test Accuracy")
plt.title("Effect of Activation Function")

plt.ylim(0, 1.05)
plt.grid(axis='y')

plt.show()

optimizers = {
    "SGD": SGD(learning_rate=0.01),
    "RMSprop": RMSprop(learning_rate=0.001),
    "Adam": Adam(learning_rate=0.001)
}

optimizer_results = []
optimizer_histories = {}

for name, optimizer in optimizers.items():

    print("\nTraining with:", name)

    temp_model = build_model(
        hidden_layers=(128, 64),
        activation='relu',
        optimizer=optimizer
    )

    temp_history = temp_model.fit(
        X_train,
        y_train_cat,
        epochs=10,
        batch_size=32,
        validation_split=0.2,
        verbose=0
    )

    loss, accuracy = temp_model.evaluate(
        X_test,
        y_test_cat,
        verbose=0
    )

    optimizer_results.append({
        "Optimizer": name,
        "Test Accuracy": accuracy,
        "Test Loss": loss,
        "Final Training Accuracy":
            temp_history.history['accuracy'][-1]
    })

    optimizer_histories[name] = temp_history

optimizer_df = pd.DataFrame(optimizer_results)

optimizer_df

plt.figure(figsize=(10, 6))

for name, history in optimizer_histories.items():

    plt.plot(
        history.history['val_accuracy'],
        label=name
    )

plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy for Different Optimizers")

plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(10, 6))

for name, history in optimizer_histories.items():

    plt.plot(
        history.history['val_loss'],
        label=name
    )

plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss for Different Optimizers")

plt.legend()
plt.grid(True)

plt.show()

# Train a model for many epochs to observe overfitting

overfit_model = build_model(
    hidden_layers=(256, 128, 64),
    activation='relu',
    optimizer='adam'
)

overfit_history = overfit_model.fit(
    X_train,
    y_train_cat,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

plt.figure(figsize=(8, 5))

plt.plot(
    overfit_history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    overfit_history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")

plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    overfit_history.history['loss'],
    label='Training Loss'
)

plt.plot(
    overfit_history.history['val_loss'],
    label='Validation Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")

plt.legend()
plt.grid(True)

plt.show()

# Early stopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

early_model = build_model(
    hidden_layers=(256, 128, 64),
    activation='relu',
    optimizer='adam'
)

early_history = early_model.fit(
    X_train,
    y_train_cat,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping],
    verbose=1
)

print("Epochs actually completed:",
      len(early_history.history['loss']))

print("Best validation loss:",
      min(early_history.history['val_loss']))

dropout_model = build_model(
    hidden_layers=(256, 128, 64),
    activation='relu',
    optimizer='adam',
    dropout_rate=0.3
)

dropout_history = dropout_model.fit(
    X_train,
    y_train_cat,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

dropout_loss, dropout_accuracy = dropout_model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("Dropout Test Accuracy:", dropout_accuracy)
print("Dropout Test Loss:", dropout_loss)

l2_model = build_model(
    hidden_layers=(256, 128, 64),
    activation='relu',
    optimizer='adam',
    l2_rate=0.001
)

l2_history = l2_model.fit(
    X_train,
    y_train_cat,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

l2_loss, l2_accuracy = l2_model.evaluate(
    X_test,
    y_test_cat,
    verbose=0
)

print("L2 Test Accuracy:", l2_accuracy)
print("L2 Test Loss:", l2_loss)

comparison = pd.DataFrame({
    "Model": [
        "Original",
        "Dropout",
        "L2 Regularization",
        "Early Stopping"
    ],

    "Test Accuracy": [
        test_accuracy,
        dropout_accuracy,
        l2_accuracy,
        early_model.evaluate(
            X_test,
            y_test_cat,
            verbose=0
        )[1]
    ]
})

comparison

plt.figure(figsize=(9, 5))

plt.bar(
    comparison["Model"],
    comparison["Test Accuracy"]
)

plt.xlabel("Model")
plt.ylabel("Test Accuracy")
plt.title("Original vs Improved Models")

plt.ylim(0, 1.05)
plt.grid(axis='y')

plt.show()